### ISSUE TITLE
Cypress recording

### ISSUE THREAD

**Issue by JoshDAO** [fac20/INCK-Front-End#25]
You can set cypress up to record all your test runs in the cypress app like this. 
![Screenshot from 2020-10-02 10-59-53](https://user-images.githubusercontent.com/55187183/94911698-6f162c00-049e-11eb-868f-6f811198db22.png)

You need to set a CYPRESS_RECORD_KEY environmental variable in travis. Should be able to find it in your project settings. You can get the value of the env variable by opening the project in the Cypress app (npx cypress open). Maybe this is helpful for you :)

**Comment by jenndroid** [comment]
We've decided against recording! thank you
